version: "3"

services:
  webserver:
    build:
      context: './docker/webserver/Dockerfile'
      dockerfile: './docker/webserver/Dockerfile'
    container_name: '${COMPOSE_PROJECT_NAME}-webserver'
    restart: 'always'
    ports:
      - '${HOST_MACHINE_UNSECURE_HOST_PORT}:80'
      - '${HOST_MACHINE_SECURE_HOST_PORT}:443'
    links:
      - 'mysql'
    volumes:
      - '${PHP_INI}:/usr/local/etc/php/php.ini'
      - '${VHOSTS_DIR}:/etc/apache2/sites-enabled'
      - '${APACHE_LOG_DIR}:/var/log/apache2'
    environment:
      APACHE_DOCUMENT_ROOT: '${APACHE_DOCUMENT_ROOT}'
      MYSQL_ROOT_PASSWORD: '${DOCKER_DB_ROOT_PASSWORD}'
  mysql:
    build:
      context: './docker/mysql/Dockerfile'
      dockerfile: './docker/mysql/Dockerfile'
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - '${MYSQL_DATA_DIR}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR}:/var/log/mysql'
      - '${MYSQL_INIT_SQL}:/tmp/database'
    command: 'mysqld --init-file="/tmp/database/init_db.sql"'
    environment:
      MYSQL_ROOT_PASSWORD: '${DOCKER_DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DOCKER_DB_DATABASE}'
      MYSQL_USER: '${DOCKER_DB_USERNAME}'
      MYSQL_PASSWORD: '${DOCKER_DB_PASSWORD}'
